# Examen 1er Bimestre

## 2) Crear un vector de ceros de tamaño 10

In [2]:
import numpy as np
import pandas as pd

In [3]:
a = np.zeros(10)

In [4]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## 3)

In [5]:
b = np.zeros(10)
b[5]= 1

In [6]:
b

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

## 4)

In [7]:
c = np.arange(50)
d = c[::-1]
d

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

## 5)

In [11]:
e = np.arange(9).reshape(3,3)
e

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 6)

In [15]:
arreglo = [1,2,0,0,4,0]

In [17]:
noCero = np.where(arreglo == 0)
noCero

(array([], dtype=int64),)

## 7)

In [20]:
identidad = np.eye(3)
identidad

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 8)

In [23]:
randomicos = np.random.randint(0,100,size=(3,3,3))
randomicos

array([[[23, 60, 94],
        [ 2, 39, 83],
        [30, 86, 49]],

       [[59, 52, 65],
        [50, 44, 34],
        [64, 12, 29]],

       [[ 5, 75, 40],
        [78, 17, 15],
        [ 5, 55, 53]]])

## 9)

In [26]:
randomicos10 = np.random.randint(0,100,size=(10,10))
randomicos10

array([[66,  6, 16, 79, 49, 22, 53, 27, 64, 44],
       [ 1, 77, 50,  7, 49, 15, 41, 13,  3, 70],
       [85, 38,  8, 37, 65, 83, 61, 90, 43, 88],
       [22, 42, 68,  8,  2, 66, 98, 68, 52, 49],
       [34, 79, 99, 48, 69, 99, 60, 45, 15, 27],
       [87, 15, 64, 81, 67, 89, 45, 33, 62, 54],
       [34, 12, 11,  3, 91, 75, 78, 29, 87, 43],
       [64, 71, 31, 97, 47, 13, 24, 85, 94, 29],
       [28, 34, 66, 88, 88, 37, 67, 63, 27, 46],
       [81, 70, 62, 14, 32, 50, 15, 74, 56, 94]])

In [27]:
randomicos10.min()

1

In [28]:
randomicos10.max()

99

## 10)

In [29]:
from scipy import ndimage
from scipy import misc

mapache = misc.face()
mapache

array([[[121, 112, 131],
        [138, 129, 148],
        [153, 144, 165],
        ...,
        [119, 126,  74],
        [131, 136,  82],
        [139, 144,  90]],

       [[ 89,  82, 100],
        [110, 103, 121],
        [130, 122, 143],
        ...,
        [118, 125,  71],
        [134, 141,  87],
        [146, 153,  99]],

       [[ 73,  66,  84],
        [ 94,  87, 105],
        [115, 108, 126],
        ...,
        [117, 126,  71],
        [133, 142,  87],
        [144, 153,  98]],

       ...,

       [[ 87, 106,  76],
        [ 94, 110,  81],
        [107, 124,  92],
        ...,
        [120, 158,  97],
        [119, 157,  96],
        [119, 158,  95]],

       [[ 85, 101,  72],
        [ 95, 111,  82],
        [112, 127,  96],
        ...,
        [121, 157,  96],
        [120, 156,  94],
        [120, 156,  94]],

       [[ 85, 101,  74],
        [ 97, 113,  84],
        [111, 126,  97],
        ...,
        [120, 156,  95],
        [119, 155,  93],
        [118, 154,  92]]

In [30]:
mapache.shape

(768, 1024, 3)

In [36]:
colores = set( tuple(v) for m2d in mapache for v in m2d )
print("Existen este numero de colores",len(colores))

Existen este numero de colores 134105


## 11)

In [48]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
myserie = pd.Series(mydict)
type(myserie)

pandas.core.series.Series

## 12)

In [72]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)
df = pd.DataFrame([ser])
df.set_index('a', inplace=True)
df.head()

b  c  e  d  f  g  h  i  j   k ...   q   r   s   t   u   v   w   x   y   z
a                                ...                                        
0  1  2  3  4  5  6  7  8  9  10 ...  16  17  18  19  20  21  22  23  24  25

[1 rows x 25 columns]

## 13)

In [83]:
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))
df13 = pd.DataFrame({'ser1': ser1, 'ser2':ser2})
df13.head(5)

ser1  ser2
0    a     0
1    b     1
2    c     2
3    e     3
4    d     4

## 14

In [90]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
ser1[ser1.isin(ser2)]

3    4
4    5
dtype: int64

## 15

In [100]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
ser1[~ser1.isin(ser2)]


0    1
1    2
2    3
dtype: int64

## 16)

In [106]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
ser.value_counts()

e    6
b    5
a    5
d    4
h    4
g    3
f    2
c    1
dtype: int64

## 17)

In [112]:
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))
masUsados=ser.value_counts()

2


## 18)

In [124]:
ser = pd.Series(np.random.randint(1, 10, 35))
h = ser.values.reshape(7,5)
df18= pd.DataFrame(h)
df18

0  1  2  3  4
0  7  5  1  6  6
1  6  2  5  1  4
2  6  9  6  9  6
3  2  9  1  5  3
4  5  5  2  2  1
5  2  2  1  4  7
6  9  3  3  1  6

## 19)

In [125]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]
ser[pos]

0     a
4     e
8     i
14    o
20    u
dtype: object

## 20)

In [147]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))
df20 = pd.DataFrame([ser1])
df20.append(ser2, ignore_index=True)

0  1  2  3  4
0  0  1  2  3  4
1  a  b  c  d  e

## 21)

In [145]:
frutas = pd.Series(np.random.choice(['manzana', 'banana', 'zanahoria'], 10))
pesos = pd.Series(np.linspace(1, 10, 10))
print(pesos.tolist())
print(frutas.tolist())



[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
['banana', 'manzana', 'banana', 'banana', 'banana', 'zanahoria', 'banana', 'banana', 'banana', 'manzana']


AttributeError: 'Series' object has no attribute 'grouby'

## 22)

In [142]:
dataset = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', usecols=["crim","zn"])
dataset.head()

crim    zn
0  0.00632  18.0
1  0.02731   0.0
2  0.02729   0.0
3  0.03237   0.0
4  0.06905   0.0